import Head from "next/head";
import SEO from "./SEO";
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import Link from 'next/link';
function WebHead({ pageTitle, data }) {

    const router = useRouter();

    useEffect(() => {
    }, [data, pageTitle]);

    return (
        <Head>
            <title>{`${pageTitle} | Luxury Ride`}</title>
            {/* <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" /> */}


            <link href="/img/lr-favicon.ico" rel="icon" media="(prefers-color-scheme: light)" />
            <link href="/img/lr-favicon-dark.ico" rel="icon" media="(prefers-color-scheme: dark)" />

            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
                integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossOrigin="anonymous" />
            <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
                integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossOrigin="anonymous"></link>
            <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />

            <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
            <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js' defer />

            <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js" defer></script>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"
            />

            <meta property="og:site_name" content="luxuryride.in" key="og-site" />
            <meta property="og:type" content="website" />
            {/* <!-- Google tag (gtag.js) --> */}
            {/* <script async src="https://www.googletagmanager.com/gtag/js?id=G-1V6VBW7YPP"></script>

            <script>
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments)}
                gtag('js', new Date());

                gtag('config', 'G-1V6VBW7YPP');
            </script> */}

            {/* &lt;!-- Google Tag Manager --&gt; */}

            {/* &lt;!-- End Google Tag Manager --&gt; */}


            {/* <!-- Google Tag Manager --> */}



            {/* <meta name="facebook-domain-verification" content="l0ev4kba947wqif9i6l8po72xdbr36" /> */}



            {/* <!-- End Google Tag Manager --> */}

            {/* <SEO /> */}

            {/* <script defer src={`https://www.googletagmanager.com/gtm.js?id=${process.env.NEXT_PUBLIC_GTM_ID}`}></script> */}

        </Head>



    )
}
export default WebHead;