import React, { useState, useRef, useEffect } from 'react';
import Head from 'next/head';
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination } from "swiper";
import 'swiper/css';
import "swiper/css/pagination";
import MultiRangeSlider from '../rangeslider/MultiRangeSlider';
import { $ } from 'react-jquery-plugin'
import WebHead from '@/components/common/WebHead';


function WarrantyPackages() {

    const [ShowOption, setShowOption] = useState(false);
    const [Readmore, setReadmore] = useState(false);
    const Moreinfo = () => {
        setReadmore(!Readmore)
    }

    const ref1 = useRef()
    useEffect(() => {
        var numToShow = 10;
        $(".list li").hide();
        $('.warranty-points ul').each(function () {
            var list = $(this).children("li");
            var button = $(this).siblings(".next-btn");
            var less = $(this).siblings('.less-btn');
            var numInList = list.length;
            less.hide();
            button.hide();
            if (numInList > numToShow) {
                button.show();
                less.hide();
            }
            //$(this).children("li:lt('+ numToShow +')").show();
            list.slice(0, numToShow).show();
        });

        $('button.next-btn').click(function () {
            var list = $(this).siblings(".list").children("li");
            var numInList = list.length;
            var showing = list.filter(':visible').length;
            list.slice(showing - 10, showing + 100).show();
            var nowShowing = list.filter(':visible').length;
            if (nowShowing >= numInList) {
                $(this).hide();
                $(this).next('button.less-btn').show();
            }
        });

        $('button.less-btn').click(function () {
            $(this).siblings(".list").children("li").not(':lt(10)').hide();
            $(this).siblings('button.next-btn').show();
            $(this).hide();
        });

        const checkIfClickedOutside1 = e => {
            // If the menu is open and the clicked target is not within the menu,
            // then close the menu
            if (ref1.current && !ref1.current.contains(e.target)) {
                setShowOption(false)
            }
        }

        document.addEventListener("mousedown", checkIfClickedOutside1)



    })

    const OpenOption = () => {

        setShowOption(!ShowOption)

    }

    const CloseMobPopup = () => {

        setShowOption(false)
    }

    return (
        <div>
            <Head>
                <title>Luxury Ride</title>
                {/* <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
                <link rel="icon" href="/lr-favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
                    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossOrigin="anonymous" />
                <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
                    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossOrigin="anonymous"></link>
                <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
            </Head>


            <WebHead />



            <section className="vehicledetailssec bg-grey comPad">
                <div className="wrapper">
                    <div className="center-text">
                        <h2>Extended Warranty For</h2>
                    </div>
                    <div className="allslctdPckg no-border">
                        <div className="col">
                            <label>Year</label>2017
                        </div>
                        <div className="col">
                            <label>Brand</label>Audi
                        </div>
                        <div className="col">
                            <label>Model</label>A3
                        </div>
                        <div className="col">
                            <label>Variant</label>35 TDI Attraction
                        </div>
                        <div className="col">
                            <label>Fuel Type</label>Diesel
                        </div>
                        <div className="col">
                            <label>KMs Driven</label>45,000
                        </div>
                        <div className="col"><a href="">Edit</a></div>
                    </div>
                </div>
            </section>

            <section className="allpackagesec comPad">
                <div className='fixed-gap extend-package'>
                    <div className="wrapper">

                        <div className="row">
                            <div className='col-md-7'>

                                <h3>Avail Luxury Ride extended warranty with exciting benefits <span>starting at 10 paisa/km</span></h3>

                                <ul>

                                    <li>Complete peace of mind </li>
                                    <li>Major parts covered </li>
                                    <li>Enhanced car resale value</li>

                                </ul>

                                <div className='greay-box'>

                                    <h3>Parts Covered Under Warranty</h3>

                                    <div className='read-data'>
                                        <p>Engine, Manual Gearbox, Automatic Gearbox, Front & Rear Wheel Drives, Propeller shaft, Steering, Braking System, Fuel System, Diesel Injection System, Air Conditioning, Electrical System

                                        </p>

                                        {Readmore ?
                                            <div className="moreTextAll" >
                                                <h3>Engine</h3>
                                                <p>Oil pump, crankshaft &amp; pulley, big end &amp; main bearings, connecting rods, gudgeon pins, piston and rings, inlet and exhaust valves (excluding burntand pitted valves), springs and guides, cylinder block and cylinder head, head gasket, camshaft, rocker arms and shaft, timing gears, tensionerbearing, inter cooler engine, water Pump (failure due to external damage or corrosion is not covered), inlet and exhaust manifold, turbo charger,elastic bolts.</p>

                                                <h3>Manual Gearbox</h3>
                                                <p>Gears, shafts, synchromesh hubs, rings, selectors, bearings, transfer gears</p>

                                                <h3>Front &amp; Rear Wheel Drives</h3>
                                                <p>Gears, differential units, wheel bearings, Axle Shafts, CV Joints</p>

                                                <h3>Propeller shaft</h3>
                                                <p>Propeller shaft, universal joints.</p>

                                                <h3>Steering</h3>
                                                <p>Rack &amp; pinion, steering column, steering box, and power steering pump, EPS</p>

                                                <h3>Braking System</h3>
                                                <p>Master cylinder, brake booster and vacuum pump, Wheel bearing, Callipers</p>

                                                <h3>Fuel System</h3>
                                                <p>Mechanical &amp; Electrical Fuel Pump, Fuel Injection Pump, Fuel accumulator, fuel distributor, fuel rail, warm up regulator, cold start valve, pressuredamper, throttle body, High and low pressure pumps</p>

                                                <h3>Diesel Injection System</h3> <p>Injection pump, electromagnetic cut off.</p>

                                                <h3>Air Conditioning</h3> <p>Compressor, condenser, evaporator, reservoir, thermostat switch, AC fan motor, heater core &amp; AC switch, Control unit , Blower motor , High and Lowpressure pipelines , Clutch magnate</p>

                                                <h3>Electrical System</h3>
                                                <p>Engine management sensors &amp; actuators, starter motor, solenoid switch, alternator, rectifier, regulator, ignition coil, cooling fan motor, powerwindow motor, power window switch, combination switch, ignition switch, fuel rail, thermostat switch, oil Pressure switch, temperature gauge, fuelgauge, Hazard switch , Electronic control unit , Body control unit , HT cable , Wiper washer motor , Immobilizer ECU,ECM, Speedometer</p>
                                            </div>
                                            : ""
                                        }
                                        <div className={Readmore ? "less-btn read-more-new" : "read-more-new"} onClick={Moreinfo}>{Readmore ? "Read Less" : "Read More"}</div>
                                    </div>


                                </div>



                                <div className="col-md-12">
                                    <a href="#" className="sky-blue-btn">Warranty Can Only Be Sold On Following Vehicles</a>
                                    <a href="#" className="sky-blue-btn">Warranty Shall Not Apply To</a>
                                </div >

                            </div>
                            <div className='col-md-5'>
                                <div className="sticky-div">
                                    <div className="packBox packBox01">

                                        <h3>Extended Warranty</h3>
                                        <div className="allPrices row">
                                            <div className="col-md-10">
                                                <form>
                                                    <div className='form-input white-bgform'>


                                                        <div className="carFiltrs custom-dropdown" ref={ref1}>

                                                            <label onClick={OpenOption} className={`${ShowOption ? "open" : ""} label`} >
                                                                (1 Year/ 10,000 Km)
                                                            </label>

                                                            {ShowOption ?
                                                                <>
                                                                    <div onClick={CloseMobPopup} className='overlay-mob'></div>
                                                                    <div className='mob-filter'>
                                                                        {/* <div className='mob-heading'>Sort By</div>       */}
                                                                        <ul className="filterListComan shortByCars">
                                                                            <li>
                                                                                <input type="radio" id="km" value="all" checked="" />
                                                                                <label htmlFor='km'>(1 Year/ 10,000 Km)</label>
                                                                            </li>

                                                                        </ul>
                                                                        <div onClick={CloseMobPopup} className='mob-close'>Close</div>
                                                                    </div>
                                                                </>

                                                                : ""}
                                                        </div>


                                                    </div>
                                                </form>



                                            </div>
                                            <div className="col-md-12 text-end">
                                                <div className="pckTxt01">Subtotal (INR) <span>Subtotal does not include applicable taxes</span></div>

                                            </div>
                                        </div>

                                        <div className='final-price'>
                                            <div className="save-text">Subtotal (INR) <span>Subtotal does not include applicable taxes</span></div>
                                            <div className="d-flex justify-content-end align-items-center price-txt">
                                                <div className="newPrice blue-txt"><span>INR </span> 79,999/-</div>
                                                <div className="oldPrice">INR 89,000</div>
                                            </div>
                                        </div>

                                        <button class="btn arrow-style blue-btn fullwd-btn"><span>Buy Now</span></button>



                                    </div >
                                </div >
                            </div>
                        </div>




                    </div >
                </div>
            </section >



        </div >
    )
}

export default WarrantyPackages
